name: Push docker image to dockerhub

on:
  push:
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: docker login -u nymann -p ${{ secrets.DOCKER_TOKEN }}
      - name: docker push
        run: make docker-push
